version: "3.5"
services:
  group-service:
    image: group-service:latest
    command: npm run dev
    ports:
      - "3000:3000"
    build:
      context: .
      target: DEV
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - PORT=3000
      - DB_SERVER=ds063789.mlab.com
      - DB_NAME=groups
      - DB_USERNAME=admin
      - DB_PASSWORD=Aa123456
      - DB_PORT=63789
