version: '3.5'
services:
  group-service:
    image: group-service:latest
    ports:
      - '3000:3000'
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - LOG_FILE_DIR=logs
      - ALLOWED_ORIGIN=http://localhost:3003
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
