version: "2.1"
services:
  group-service:
    container_name: group-service
    image: group-service:latest
    ports:
      - "3000:3000"
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    # environment:
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
