version: "2.1"
services:
  hierarchy-service:
    container_name: hierarchy-service
    image: hierarchy-service:latest
    ports:
        - '3000:3000'
    build: . 
    volumes:
        - ./src:/usr/app/src
    environment:
      KARTOFFEL_API: "http://kartoffel-master.eastus.cloudapp.azure.com:3000/api"
    restart: always

  