version: "2.1"
services:
  hierarchy-service:
    container_name: hierarchy-service
    image: hierarchy-service:latest
    command: npm run dev:watch # Hot reload
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src # share src code with the containers
    environment:
      KARTOFFEL_API: "http://kartoffel-master.eastus.cloudapp.azure.com:3000/api"
    restart: always
