version: '3.5'
services:
  group-service:
    container_name: group-service
    image: group-service:latest
    command: npm run dev:watch # Hot reload
    ports:
      - '3000:3000'
    build:
      context: .
      target: DEV
    volumes:
      - ./src:/usr/src/app/src # share src code with the containers
    # environment:
    restart: always
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
